### ISSUE TITLE
grails.assets properties does not work

### ISSUE THREAD

**Issue by dalibor983** [bertramdev/asset-pipeline#254]
I tried to use
```
grails.assets.minifyJs = false
grails.assets.minifyCss = false
grails.assets.bundle = false
```
in grails 3.0.1

And put all of these in application.yml file like this
```yml
grails:
  assets:
    minifyJs: false
    minifyCss: false
    bundle: false
```
and I always got minified and bundled css and js files.

The only way to get not minified assets is to put this configuration in gradle build config:
```
assets {
    minifyJs = false
    minifyCss = false
}
```
But I cannot get unbundled script and link generation in gsp pages.
