### ISSUE TITLE
css background-image url translation broken when going several levels deep

### ISSUE THREAD

**Issue by martijnkorteweg** [bertramdev/asset-pipeline#261]
Asset-pipeline: 2.3.0 / 2.3.2
Grails: 2.5.0

When you go several level deep on a relative path, the url no longer gets translated to the correct path. I noticed this breaking when upgrading from 1.9.4 -> 2.3.0. Also just tested it on 2.3.2 and it shows the same results

#### source css example 1
```css
.image-class {
    background-image: url('../../images/image.png');
}
```
Translation for example 1 will not have any changes in the url to correct the image path

#### source css example 2
```css
.image-class {
    background-image: url('../images/image.png');
}
```
Translates the single depth folder correctly to:
```css
.image-class {
    background-image: url('image.png');
}
```
